<center><h1>Raport NLP</h1></center>
<center><h2>Porównanie modeli BERT z LSTM (w tym BERT rozmiaru LSTM)</h2></center>
<ol>
  <li>Konrad Orzełowski</li>
  <li>Michał Kozak</li>
</ol>

Link do projektu na platformie Kaggle: https://www.kaggle.com/code/michaldao54/bert-projekt/edit

<h3>Użyte zbiory danych:</h3>
<ol>
  <li>Emotions - https://www.kaggle.com/datasets/praveengovi/emotions-dataset-for-nlp</li>
  <li>SMSSpam - https://www.kaggle.com/uciml/sms-spam-collection-dataset</li>
  <li>BBC news - http://mlg.ucd.ie/datasets/bbc.html</li>
  <li>IMDB - https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews </li>
  <li>DisasterTweets - https://www.kaggle.com/c/nlp-getting-started/</li>   
</ol>
<h3></h3>


|    **Zbiór**   | **Średnia liczba wyrazów** | **Maksymalna liczba wyrazów** |
|:--------------:|:--------------------------:|:-----------------------------:|
|    Emotions    |             96             |              300              |
|     SMSSpam    |             80             |              910              |
|    BBC news    |            2262            |             25483             |
|      IMDB      |            1309            |             13704             |
| DisasterTweets |             101            |              157              |


<h3>Użyte modele:</h3>

|  **Model**  | **Liczba parametrów (mln)** |
|:-----------:|:---------------------------:|
|  BERT Large (L=24, H=1024, A=16)|             340             |
| BERT Normal (L=12, H=768, A=12) |             110             |
|  BERT Tiny (L=2, H=128, A=2) |             4.4             |
|     LSTM (3 Warstwy po 192 komórki - Keras)    |             4.5             |

L-liczba warstw enkodera transformera</br>
H-dlugość wektora ukrytego</br>
A-liczba głów atencji

Komórki LSTM - zwykłe z biblioteki keras

<h3>Generalne informacje o treningu i wstępnym przetwarzaniu danych:</h3>
<ol>
<li>Nie zastosowano obróbki wstępnej danych dla żadnego zbioru.</li>
<li>Podział zbioru: 60% zbiór treningowy, 20% zbiór walidacyjny, 20% zbiór testowy (random state = 303).</li>
<li>BERT: Współczynnik uczenia 2e-05, weight decay 1e-02, algorytm uczenia AdamW, sposób treningu - fine-tuning (transfer learning) + classification head. Batch size 32, lecz czasem 16 aby wystarczyło pamięci GPU. Źródło modeli BERT do transfer learning https://huggingface.co/prajjwal1/bert-tiny</li>
<li>LSTM: Współczynnik uczenia 1e-04, algorytm uczenia Adam, sposób treningu - from scratch, batch size 16. Architektura: 3 warstwy po 192 komórki LSTM każda. </li>
<li>Wykorzystane GPU: NVIDIA TESLA P100  16GB, czas obliczeń 200h.</li>

</ol>

In [ ]:
import pandas as pd
df = pd.read_csv('all_results.csv', index_col=False)
df = df.round({'test_loss': 3, 'test_acc': 3, 'precision': 3, 'recall': 3, 'f1': 10, 'test_runtime': 3, 'test_samples_per_second': 3, 'test_steps_per_second': 3, 'batch_size': 3})

# Wyniki uzyskane dla zbioru Emotions

In [ ]:
Emotions = df[df["dataset"] == "Emotions"]
display(Emotions.sort_values(["test_acc"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
59,LSTM,100.0,50,Emotions,5.0,0.170,0.935,0.935,0.935,0.935063,NaN,NaN,NaN,16.0
69,LSTM,100.0,50,Emotions,5.0,0.170,0.935,0.935,0.935,0.935063,NaN,NaN,NaN,16.0
10,BERT large,NaN,200,Emotions,NaN,0.155,0.934,0.933,0.934,0.932427,15.437,129.560,4.081,NaN
74,LSTM,100.0,100,Emotions,9.0,0.171,0.933,0.933,0.933,0.932717,NaN,NaN,NaN,16.0
64,LSTM,100.0,100,Emotions,9.0,0.171,0.933,0.933,0.933,0.932717,NaN,NaN,NaN,16.0
11,BERT large,NaN,350,Emotions,NaN,0.164,0.932,0.932,0.932,0.931156,15.300,130.715,4.118,NaN
5,BERT normal,NaN,100,Emotions,4.0,0.165,0.932,0.933,0.932,0.930626,5.005,399.620,6.394,NaN
6,BERT normal,NaN,200,Emotions,4.0,0.165,0.932,0.933,0.932,0.930626,5.053,395.775,6.332,NaN
7,BERT normal,NaN,350,Emotions,4.0,0.165,0.932,0.933,0.932,0.930626,5.090,392.916,6.287,NaN
9,BERT large,NaN,100,Emotions,NaN,0.152,0.931,0.930,0.931,0.930078,15.282,130.871,4.122,NaN
79,LSTM,200.0,100,Emotions,8.0,0.245,0.930,0.930,0.930,0.930230,NaN,NaN,NaN,16.0
107,LSTM,200.0,350,Emotions,31.0,0.228,0.927,0.927,0.927,0.927079,NaN,NaN,NaN,16.0
8,BERT large,NaN,50,Emotions,4.0,0.154,0.926,0.927,0.926,0.924643,10.914,183.258,5.773,NaN
4,BERT normal,NaN,50,Emotions,4.0,0.177,0.926,0.927,0.926,0.924939,4.181,478.347,7.654,NaN
84,LSTM,200.0,50,Emotions,6.0,0.265,0.925,0.926,0.926,0.925216,NaN,NaN,NaN,16.0
92,LSTM,200.0,200,Emotions,24.0,0.234,0.922,0.923,0.922,0.921775,NaN,NaN,NaN,16.0
102,LSTM,300.0,500,Emotions,18.0,0.232,0.920,0.920,0.920,0.919920,NaN,NaN,NaN,16.0
97,LSTM,300.0,200,Emotions,15.0,0.256,0.917,0.917,0.917,0.916278,NaN,NaN,NaN,16.0
1,BERT tiny,NaN,100,Emotions,47.0,0.250,0.904,0.906,0.904,0.904895,1.191,1679.785,26.877,NaN
3,BERT tiny,NaN,350,Emotions,47.0,0.250,0.904,0.906,0.904,0.904895,1.131,1768.215,28.291,NaN
2,BERT tiny,NaN,200,Emotions,47.0,0.250,0.904,0.906,0.904,0.904895,1.128,1772.962,28.367,NaN
0,BERT tiny,NaN,50,Emotions,41.0,0.264,0.899,0.902,0.899,0.900018,1.079,1852.925,29.647,NaN

In [ ]:
display(Emotions.sort_values(["f1"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
59,LSTM,100.0,50,Emotions,5.0,0.170,0.935,0.935,0.935,0.935063,NaN,NaN,NaN,16.0
69,LSTM,100.0,50,Emotions,5.0,0.170,0.935,0.935,0.935,0.935063,NaN,NaN,NaN,16.0
74,LSTM,100.0,100,Emotions,9.0,0.171,0.933,0.933,0.933,0.932717,NaN,NaN,NaN,16.0
64,LSTM,100.0,100,Emotions,9.0,0.171,0.933,0.933,0.933,0.932717,NaN,NaN,NaN,16.0
10,BERT large,NaN,200,Emotions,NaN,0.155,0.934,0.933,0.934,0.932427,15.437,129.560,4.081,NaN
11,BERT large,NaN,350,Emotions,NaN,0.164,0.932,0.932,0.932,0.931156,15.300,130.715,4.118,NaN
5,BERT normal,NaN,100,Emotions,4.0,0.165,0.932,0.933,0.932,0.930626,5.005,399.620,6.394,NaN
6,BERT normal,NaN,200,Emotions,4.0,0.165,0.932,0.933,0.932,0.930626,5.053,395.775,6.332,NaN
7,BERT normal,NaN,350,Emotions,4.0,0.165,0.932,0.933,0.932,0.930626,5.090,392.916,6.287,NaN
79,LSTM,200.0,100,Emotions,8.0,0.245,0.930,0.930,0.930,0.930230,NaN,NaN,NaN,16.0
9,BERT large,NaN,100,Emotions,NaN,0.152,0.931,0.930,0.931,0.930078,15.282,130.871,4.122,NaN
107,LSTM,200.0,350,Emotions,31.0,0.228,0.927,0.927,0.927,0.927079,NaN,NaN,NaN,16.0
84,LSTM,200.0,50,Emotions,6.0,0.265,0.925,0.926,0.926,0.925216,NaN,NaN,NaN,16.0
4,BERT normal,NaN,50,Emotions,4.0,0.177,0.926,0.927,0.926,0.924939,4.181,478.347,7.654,NaN
8,BERT large,NaN,50,Emotions,4.0,0.154,0.926,0.927,0.926,0.924643,10.914,183.258,5.773,NaN
92,LSTM,200.0,200,Emotions,24.0,0.234,0.922,0.923,0.922,0.921775,NaN,NaN,NaN,16.0
102,LSTM,300.0,500,Emotions,18.0,0.232,0.920,0.920,0.920,0.919920,NaN,NaN,NaN,16.0
97,LSTM,300.0,200,Emotions,15.0,0.256,0.917,0.917,0.917,0.916278,NaN,NaN,NaN,16.0
1,BERT tiny,NaN,100,Emotions,47.0,0.250,0.904,0.906,0.904,0.904895,1.191,1679.785,26.877,NaN
3,BERT tiny,NaN,350,Emotions,47.0,0.250,0.904,0.906,0.904,0.904895,1.131,1768.215,28.291,NaN
2,BERT tiny,NaN,200,Emotions,47.0,0.250,0.904,0.906,0.904,0.904895,1.128,1772.962,28.367,NaN
0,BERT tiny,NaN,50,Emotions,41.0,0.264,0.899,0.902,0.899,0.900018,1.079,1852.925,29.647,NaN

# Wyniki uzyskane dla zbioru SpamSMS

In [ ]:
SMSSpam = df[df["dataset"] == "SMSSpam"]
display(SMSSpam.sort_values(["test_acc"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
14,BERT tiny,NaN,200,SMSSpam,17.0,0.017,0.996,0.996,0.996,0.996401,0.585,1905.292,59.807,NaN
16,BERT tiny,NaN,500,SMSSpam,35.0,0.018,0.996,0.996,0.996,0.996401,0.591,1886.133,59.206,NaN
20,BERT normal,NaN,350,SMSSpam,NaN,0.023,0.996,0.996,0.996,0.995509,6.926,160.977,5.053,NaN
21,BERT normal,NaN,500,SMSSpam,NaN,0.023,0.996,0.996,0.996,0.995509,6.910,161.361,5.065,NaN
22,BERT large,NaN,50,SMSSpam,NaN,0.032,0.996,0.996,0.996,0.995481,6.076,183.493,5.760,32.0
24,BERT large,NaN,200,SMSSpam,NaN,0.033,0.995,0.995,0.995,0.994602,22.210,50.202,3.152,16.0
15,BERT tiny,NaN,350,SMSSpam,19.0,0.027,0.995,0.995,0.995,0.994619,0.576,1937.309,60.812,NaN
18,BERT normal,NaN,100,SMSSpam,NaN,0.023,0.995,0.995,0.995,0.994619,4.003,278.530,8.743,NaN
17,BERT normal,NaN,50,SMSSpam,NaN,0.035,0.994,0.994,0.994,0.993732,2.806,397.297,12.471,NaN
19,BERT normal,NaN,200,SMSSpam,NaN,0.028,0.994,0.994,0.994,0.993712,6.950,160.431,5.036,NaN
13,BERT tiny,NaN,100,SMSSpam,15.0,0.024,0.994,0.994,0.994,0.993712,0.571,1952.971,61.304,NaN
12,BERT tiny,NaN,50,SMSSpam,14.0,0.033,0.993,0.993,0.993,0.992825,0.524,2128.482,66.813,NaN
23,BERT large,NaN,100,SMSSpam,NaN,0.049,0.992,0.992,0.992,0.991941,11.439,97.473,3.060,NaN
67,LSTM,100.0,100,SMSSpam,11.0,0.076,0.990,0.990,0.990,0.990089,NaN,NaN,NaN,16.0
77,LSTM,100.0,100,SMSSpam,11.0,0.076,0.990,0.990,0.990,0.990089,NaN,NaN,NaN,16.0
62,LSTM,100.0,50,SMSSpam,8.0,0.081,0.989,0.989,0.989,0.989137,NaN,NaN,NaN,16.0
72,LSTM,100.0,50,SMSSpam,8.0,0.081,0.989,0.989,0.989,0.989137,NaN,NaN,NaN,16.0
82,LSTM,200.0,100,SMSSpam,6.0,0.078,0.987,0.987,0.987,0.987327,NaN,NaN,NaN,16.0
103,LSTM,300.0,500,SMSSpam,14.0,0.090,0.987,0.986,0.987,0.986356,NaN,NaN,NaN,16.0
87,LSTM,200.0,50,SMSSpam,3.0,0.072,0.986,0.986,0.986,0.985693,NaN,NaN,NaN,16.0
98,LSTM,300.0,200,SMSSpam,19.0,0.114,0.986,0.986,0.986,0.985470,NaN,NaN,NaN,16.0
93,LSTM,200.0,200,SMSSpam,11.0,0.064,0.982,0.982,0.982,0.982008,NaN,NaN,NaN,16.0
109,LSTM,200.0,350,SMSSpam,12.0,0.092,0.979,0.980,0.979,0.979525,NaN,NaN,NaN,16.0

In [ ]:
display(SMSSpam.sort_values(["f1"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
14,BERT tiny,NaN,200,SMSSpam,17.0,0.017,0.996,0.996,0.996,0.996401,0.585,1905.292,59.807,NaN
16,BERT tiny,NaN,500,SMSSpam,35.0,0.018,0.996,0.996,0.996,0.996401,0.591,1886.133,59.206,NaN
20,BERT normal,NaN,350,SMSSpam,NaN,0.023,0.996,0.996,0.996,0.995509,6.926,160.977,5.053,NaN
21,BERT normal,NaN,500,SMSSpam,NaN,0.023,0.996,0.996,0.996,0.995509,6.910,161.361,5.065,NaN
22,BERT large,NaN,50,SMSSpam,NaN,0.032,0.996,0.996,0.996,0.995481,6.076,183.493,5.760,32.0
15,BERT tiny,NaN,350,SMSSpam,19.0,0.027,0.995,0.995,0.995,0.994619,0.576,1937.309,60.812,NaN
18,BERT normal,NaN,100,SMSSpam,NaN,0.023,0.995,0.995,0.995,0.994619,4.003,278.530,8.743,NaN
24,BERT large,NaN,200,SMSSpam,NaN,0.033,0.995,0.995,0.995,0.994602,22.210,50.202,3.152,16.0
17,BERT normal,NaN,50,SMSSpam,NaN,0.035,0.994,0.994,0.994,0.993732,2.806,397.297,12.471,NaN
19,BERT normal,NaN,200,SMSSpam,NaN,0.028,0.994,0.994,0.994,0.993712,6.950,160.431,5.036,NaN
13,BERT tiny,NaN,100,SMSSpam,15.0,0.024,0.994,0.994,0.994,0.993712,0.571,1952.971,61.304,NaN
12,BERT tiny,NaN,50,SMSSpam,14.0,0.033,0.993,0.993,0.993,0.992825,0.524,2128.482,66.813,NaN
23,BERT large,NaN,100,SMSSpam,NaN,0.049,0.992,0.992,0.992,0.991941,11.439,97.473,3.060,NaN
67,LSTM,100.0,100,SMSSpam,11.0,0.076,0.990,0.990,0.990,0.990089,NaN,NaN,NaN,16.0
77,LSTM,100.0,100,SMSSpam,11.0,0.076,0.990,0.990,0.990,0.990089,NaN,NaN,NaN,16.0
62,LSTM,100.0,50,SMSSpam,8.0,0.081,0.989,0.989,0.989,0.989137,NaN,NaN,NaN,16.0
72,LSTM,100.0,50,SMSSpam,8.0,0.081,0.989,0.989,0.989,0.989137,NaN,NaN,NaN,16.0
82,LSTM,200.0,100,SMSSpam,6.0,0.078,0.987,0.987,0.987,0.987327,NaN,NaN,NaN,16.0
103,LSTM,300.0,500,SMSSpam,14.0,0.090,0.987,0.986,0.987,0.986356,NaN,NaN,NaN,16.0
87,LSTM,200.0,50,SMSSpam,3.0,0.072,0.986,0.986,0.986,0.985693,NaN,NaN,NaN,16.0
98,LSTM,300.0,200,SMSSpam,19.0,0.114,0.986,0.986,0.986,0.985470,NaN,NaN,NaN,16.0
93,LSTM,200.0,200,SMSSpam,11.0,0.064,0.982,0.982,0.982,0.982008,NaN,NaN,NaN,16.0
109,LSTM,200.0,350,SMSSpam,12.0,0.092,0.979,0.980,0.979,0.979525,NaN,NaN,NaN,16.0

# Wyniki uzyskane dla zbioru BBC news

In [ ]:
BBC_news = df[df["dataset"] == "BBC_news"]
display(BBC_news.sort_values(["test_acc"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
34,BERT normal,NaN,500,BBC_news,5.0,0.059,0.987,0.987,0.987,0.986524,14.011,79.439,4.996,16.0
33,BERT normal,NaN,350,BBC_news,5.0,0.054,0.986,0.986,0.986,0.985623,20.391,54.584,3.433,16.0
36,BERT large,NaN,100,BBC_news,5.0,0.065,0.985,0.985,0.985,0.984725,11.619,95.788,3.012,32.0
31,BERT normal,NaN,100,BBC_news,5.0,0.071,0.985,0.985,0.985,0.984715,3.988,279.085,8.776,32.0
29,BERT tiny,NaN,500,BBC_news,NaN,0.072,0.982,0.982,0.982,0.981998,0.909,1224.195,38.497,NaN
32,BERT normal,NaN,200,BBC_news,5.0,0.068,0.982,0.982,0.982,0.982044,7.435,149.691,4.707,32.0
35,BERT large,NaN,50,BBC_news,NaN,0.087,0.978,0.978,0.978,0.977559,6.053,183.871,5.782,32.0
28,BERT tiny,NaN,350,BBC_news,130.0,0.083,0.978,0.979,0.978,0.978471,0.752,1480.512,46.557,NaN
30,BERT normal,NaN,50,BBC_news,5.0,0.089,0.978,0.978,0.978,0.977565,2.196,506.769,15.936,32.0
27,BERT tiny,NaN,200,BBC_news,130.0,0.113,0.972,0.972,0.972,0.972145,0.608,1831.636,57.599,NaN
26,BERT tiny,NaN,100,BBC_news,130.0,0.120,0.971,0.971,0.971,0.971233,0.523,2127.638,66.907,NaN
25,BERT tiny,NaN,50,BBC_news,130.0,0.149,0.963,0.963,0.963,0.963153,0.605,1840.300,57.871,NaN
101,LSTM,300.0,500,BBC_news,21.0,0.162,0.948,0.948,0.948,0.948355,NaN,NaN,NaN,16.0
91,LSTM,200.0,200,BBC_news,12.0,0.225,0.944,0.944,0.944,0.943805,NaN,NaN,NaN,16.0
96,LSTM,300.0,200,BBC_news,17.0,0.289,0.937,0.939,0.937,0.937200,NaN,NaN,NaN,16.0
65,LSTM,100.0,100,BBC_news,18.0,0.347,0.928,0.928,0.928,0.928002,NaN,NaN,NaN,16.0
75,LSTM,100.0,100,BBC_news,18.0,0.347,0.928,0.928,0.928,0.928002,NaN,NaN,NaN,16.0
60,LSTM,100.0,50,BBC_news,11.0,0.359,0.921,0.921,0.921,0.920942,NaN,NaN,NaN,16.0
70,LSTM,100.0,50,BBC_news,11.0,0.359,0.921,0.921,0.921,0.920942,NaN,NaN,NaN,16.0
80,LSTM,200.0,100,BBC_news,6.0,0.339,0.921,0.921,0.921,0.921127,NaN,NaN,NaN,16.0
85,LSTM,200.0,50,BBC_news,5.0,0.700,0.867,0.887,0.867,0.864932,NaN,NaN,NaN,16.0

In [ ]:
display(BBC_news.sort_values(["f1"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
34,BERT normal,NaN,500,BBC_news,5.0,0.059,0.987,0.987,0.987,0.986524,14.011,79.439,4.996,16.0
33,BERT normal,NaN,350,BBC_news,5.0,0.054,0.986,0.986,0.986,0.985623,20.391,54.584,3.433,16.0
36,BERT large,NaN,100,BBC_news,5.0,0.065,0.985,0.985,0.985,0.984725,11.619,95.788,3.012,32.0
31,BERT normal,NaN,100,BBC_news,5.0,0.071,0.985,0.985,0.985,0.984715,3.988,279.085,8.776,32.0
32,BERT normal,NaN,200,BBC_news,5.0,0.068,0.982,0.982,0.982,0.982044,7.435,149.691,4.707,32.0
29,BERT tiny,NaN,500,BBC_news,NaN,0.072,0.982,0.982,0.982,0.981998,0.909,1224.195,38.497,NaN
28,BERT tiny,NaN,350,BBC_news,130.0,0.083,0.978,0.979,0.978,0.978471,0.752,1480.512,46.557,NaN
30,BERT normal,NaN,50,BBC_news,5.0,0.089,0.978,0.978,0.978,0.977565,2.196,506.769,15.936,32.0
35,BERT large,NaN,50,BBC_news,NaN,0.087,0.978,0.978,0.978,0.977559,6.053,183.871,5.782,32.0
27,BERT tiny,NaN,200,BBC_news,130.0,0.113,0.972,0.972,0.972,0.972145,0.608,1831.636,57.599,NaN
26,BERT tiny,NaN,100,BBC_news,130.0,0.120,0.971,0.971,0.971,0.971233,0.523,2127.638,66.907,NaN
25,BERT tiny,NaN,50,BBC_news,130.0,0.149,0.963,0.963,0.963,0.963153,0.605,1840.300,57.871,NaN
101,LSTM,300.0,500,BBC_news,21.0,0.162,0.948,0.948,0.948,0.948355,NaN,NaN,NaN,16.0
91,LSTM,200.0,200,BBC_news,12.0,0.225,0.944,0.944,0.944,0.943805,NaN,NaN,NaN,16.0
96,LSTM,300.0,200,BBC_news,17.0,0.289,0.937,0.939,0.937,0.937200,NaN,NaN,NaN,16.0
65,LSTM,100.0,100,BBC_news,18.0,0.347,0.928,0.928,0.928,0.928002,NaN,NaN,NaN,16.0
75,LSTM,100.0,100,BBC_news,18.0,0.347,0.928,0.928,0.928,0.928002,NaN,NaN,NaN,16.0
80,LSTM,200.0,100,BBC_news,6.0,0.339,0.921,0.921,0.921,0.921127,NaN,NaN,NaN,16.0
60,LSTM,100.0,50,BBC_news,11.0,0.359,0.921,0.921,0.921,0.920942,NaN,NaN,NaN,16.0
70,LSTM,100.0,50,BBC_news,11.0,0.359,0.921,0.921,0.921,0.920942,NaN,NaN,NaN,16.0
85,LSTM,200.0,50,BBC_news,5.0,0.700,0.867,0.887,0.867,0.864932,NaN,NaN,NaN,16.0

# Wyniki uzyskane dla zbioru IMDB

In [ ]:
IMDBDataset = df[df["dataset"] == "IMDBDataset"]
display(IMDBDataset.sort_values(["test_acc"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
46,BERT normal,NaN,500,IMDBDataset,1.0,0.186,0.931,0.931,0.931,0.931109,230.098,54.325,3.399,16.0
45,BERT normal,NaN,350,IMDBDataset,2.0,0.203,0.929,0.929,0.929,0.928880,154.840,80.728,5.050,16.0
49,BERT large,NaN,200,IMDBDataset,10.0,0.208,0.917,0.918,0.917,0.917209,261.734,47.758,2.988,16.0
44,BERT normal,NaN,200,IMDBDataset,2.0,0.235,0.912,0.912,0.912,0.911989,83.484,149.729,4.684,NaN
90,LSTM,200.0,500,IMDBDataset,46.0,0.264,0.902,0.902,0.902,0.901996,NaN,NaN,NaN,16.0
108,LSTM,200.0,350,IMDBDataset,9.0,0.388,0.902,0.902,0.902,0.901599,NaN,NaN,NaN,16.0
105,LSTM,300.0,500,IMDBDataset,7.0,0.505,0.892,0.892,0.892,0.891684,NaN,NaN,NaN,16.0
95,LSTM,200.0,200,IMDBDataset,8.0,0.375,0.890,0.891,0.890,0.890440,NaN,NaN,NaN,16.0
48,BERT large,NaN,100,IMDBDataset,1.0,0.289,0.876,0.879,0.876,0.875663,126.676,98.677,3.087,32.0
100,LSTM,300.0,200,IMDBDataset,4.0,0.537,0.876,0.882,0.876,0.876048,NaN,NaN,NaN,16.0
43,BERT normal,NaN,100,IMDBDataset,2.0,0.322,0.875,0.875,0.875,0.875042,44.385,281.625,8.809,NaN
41,BERT tiny,NaN,500,IMDBDataset,5.0,0.323,0.867,0.867,0.867,0.866956,10.191,1226.542,38.366,NaN
40,BERT tiny,NaN,350,IMDBDataset,5.0,0.332,0.866,0.866,0.866,0.865683,8.103,1542.599,48.252,NaN
83,LSTM,200.0,100,IMDBDataset,1.0,0.997,0.851,0.851,0.851,0.850687,NaN,NaN,NaN,16.0
68,LSTM,100.0,100,IMDBDataset,1.0,0.866,0.847,0.849,0.847,0.847260,NaN,NaN,NaN,16.0
78,LSTM,100.0,100,IMDBDataset,1.0,0.866,0.847,0.849,0.847,0.847260,NaN,NaN,NaN,16.0
39,BERT tiny,NaN,200,IMDBDataset,5.0,0.367,0.842,0.843,0.842,0.842294,6.479,1929.278,60.348,NaN
47,BERT large,NaN,50,IMDBDataset,1.0,0.396,0.840,0.840,0.840,0.840243,67.969,183.907,5.753,32.0
42,BERT normal,NaN,50,IMDBDataset,2.0,0.403,0.821,0.821,0.821,0.820798,27.804,449.567,14.062,NaN
73,LSTM,100.0,50,IMDBDataset,2.0,0.963,0.809,0.809,0.809,0.809200,NaN,NaN,NaN,16.0
63,LSTM,100.0,50,IMDBDataset,2.0,0.963,0.809,0.809,0.809,0.809200,NaN,NaN,NaN,16.0
88,LSTM,200.0,50,IMDBDataset,1.0,1.225,0.807,0.808,0.807,0.806762,NaN,NaN,NaN,16.0
38,BERT tiny,NaN,100,IMDBDataset,NaN,0.445,0.795,0.796,0.795,0.795419,5.741,2177.370,68.108,NaN
37,BERT tiny,NaN,50,IMDBDataset,NaN,0.530,0.735,0.735,0.735,0.735198,6.000,2083.212,65.163,NaN

In [ ]:
display(IMDBDataset.sort_values(["f1"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
46,BERT normal,NaN,500,IMDBDataset,1.0,0.186,0.931,0.931,0.931,0.931109,230.098,54.325,3.399,16.0
45,BERT normal,NaN,350,IMDBDataset,2.0,0.203,0.929,0.929,0.929,0.928880,154.840,80.728,5.050,16.0
49,BERT large,NaN,200,IMDBDataset,10.0,0.208,0.917,0.918,0.917,0.917209,261.734,47.758,2.988,16.0
44,BERT normal,NaN,200,IMDBDataset,2.0,0.235,0.912,0.912,0.912,0.911989,83.484,149.729,4.684,NaN
90,LSTM,200.0,500,IMDBDataset,46.0,0.264,0.902,0.902,0.902,0.901996,NaN,NaN,NaN,16.0
108,LSTM,200.0,350,IMDBDataset,9.0,0.388,0.902,0.902,0.902,0.901599,NaN,NaN,NaN,16.0
105,LSTM,300.0,500,IMDBDataset,7.0,0.505,0.892,0.892,0.892,0.891684,NaN,NaN,NaN,16.0
95,LSTM,200.0,200,IMDBDataset,8.0,0.375,0.890,0.891,0.890,0.890440,NaN,NaN,NaN,16.0
100,LSTM,300.0,200,IMDBDataset,4.0,0.537,0.876,0.882,0.876,0.876048,NaN,NaN,NaN,16.0
48,BERT large,NaN,100,IMDBDataset,1.0,0.289,0.876,0.879,0.876,0.875663,126.676,98.677,3.087,32.0
43,BERT normal,NaN,100,IMDBDataset,2.0,0.322,0.875,0.875,0.875,0.875042,44.385,281.625,8.809,NaN
41,BERT tiny,NaN,500,IMDBDataset,5.0,0.323,0.867,0.867,0.867,0.866956,10.191,1226.542,38.366,NaN
40,BERT tiny,NaN,350,IMDBDataset,5.0,0.332,0.866,0.866,0.866,0.865683,8.103,1542.599,48.252,NaN
83,LSTM,200.0,100,IMDBDataset,1.0,0.997,0.851,0.851,0.851,0.850687,NaN,NaN,NaN,16.0
68,LSTM,100.0,100,IMDBDataset,1.0,0.866,0.847,0.849,0.847,0.847260,NaN,NaN,NaN,16.0
78,LSTM,100.0,100,IMDBDataset,1.0,0.866,0.847,0.849,0.847,0.847260,NaN,NaN,NaN,16.0
39,BERT tiny,NaN,200,IMDBDataset,5.0,0.367,0.842,0.843,0.842,0.842294,6.479,1929.278,60.348,NaN
47,BERT large,NaN,50,IMDBDataset,1.0,0.396,0.840,0.840,0.840,0.840243,67.969,183.907,5.753,32.0
42,BERT normal,NaN,50,IMDBDataset,2.0,0.403,0.821,0.821,0.821,0.820798,27.804,449.567,14.062,NaN
73,LSTM,100.0,50,IMDBDataset,2.0,0.963,0.809,0.809,0.809,0.809200,NaN,NaN,NaN,16.0
63,LSTM,100.0,50,IMDBDataset,2.0,0.963,0.809,0.809,0.809,0.809200,NaN,NaN,NaN,16.0
88,LSTM,200.0,50,IMDBDataset,1.0,1.225,0.807,0.808,0.807,0.806762,NaN,NaN,NaN,16.0
38,BERT tiny,NaN,100,IMDBDataset,NaN,0.445,0.795,0.796,0.795,0.795419,5.741,2177.370,68.108,NaN
37,BERT tiny,NaN,50,IMDBDataset,NaN,0.530,0.735,0.735,0.735,0.735198,6.000,2083.212,65.163,NaN

# Wyniki uzyskane dla zbioru DisasterTweets

In [ ]:
DisasterTweets = df[df["dataset"] == "DisasterTweets"]
display(DisasterTweets.sort_values(["test_acc"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
58,BERT large,NaN,159,DisasterTweets,NaN,0.376,0.856,0.855,0.856,0.855059,13.824,110.172,3.472,NaN
55,BERT normal,NaN,159,DisasterTweets,2.0,0.375,0.855,0.855,0.855,0.853981,5.155,295.430,9.311,NaN
56,BERT large,NaN,50,DisasterTweets,2.0,0.401,0.854,0.855,0.854,0.854368,8.282,183.887,5.796,NaN
54,BERT normal,NaN,100,DisasterTweets,2.0,0.389,0.850,0.850,0.850,0.849825,5.331,285.702,9.004,NaN
53,BERT normal,NaN,50,DisasterTweets,2.0,0.395,0.848,0.850,0.848,0.848756,2.962,514.246,16.207,NaN
57,BERT large,NaN,100,DisasterTweets,NaN,0.378,0.844,0.844,0.844,0.844293,13.765,110.645,3.487,NaN
50,BERT tiny,NaN,50,DisasterTweets,10.0,0.411,0.833,0.832,0.833,0.832071,0.822,1852.849,58.396,NaN
52,BERT tiny,NaN,159,DisasterTweets,10.0,0.406,0.833,0.833,0.833,0.832151,0.735,2071.001,65.271,NaN
51,BERT tiny,NaN,100,DisasterTweets,10.0,0.407,0.833,0.832,0.833,0.831407,0.896,1699.858,53.574,NaN
89,LSTM,200.0,500,DisasterTweets,24.0,0.486,0.785,0.777,0.785,0.778389,NaN,NaN,NaN,16.0
94,LSTM,200.0,200,DisasterTweets,4.0,0.573,0.760,0.755,0.760,0.756910,NaN,NaN,NaN,16.0
99,LSTM,300.0,200,DisasterTweets,4.0,0.619,0.759,0.752,0.759,0.754329,NaN,NaN,NaN,16.0
104,LSTM,300.0,500,DisasterTweets,2.0,0.646,0.755,0.748,0.755,0.750053,NaN,NaN,NaN,16.0
106,LSTM,200.0,350,DisasterTweets,4.0,0.618,0.744,0.744,0.744,0.744485,NaN,NaN,NaN,16.0
81,LSTM,200.0,100,DisasterTweets,1.0,1.038,0.735,0.722,0.735,0.725275,NaN,NaN,NaN,16.0
86,LSTM,200.0,50,DisasterTweets,1.0,1.010,0.724,0.731,0.724,0.727318,NaN,NaN,NaN,16.0
76,LSTM,100.0,100,DisasterTweets,2.0,0.782,0.712,0.742,0.712,0.720947,NaN,NaN,NaN,16.0
66,LSTM,100.0,100,DisasterTweets,2.0,0.782,0.712,0.742,0.712,0.720947,NaN,NaN,NaN,16.0
71,LSTM,100.0,50,DisasterTweets,1.0,0.958,0.681,0.634,0.681,0.633678,NaN,NaN,NaN,16.0
61,LSTM,100.0,50,DisasterTweets,1.0,0.958,0.681,0.634,0.681,0.633678,NaN,NaN,NaN,16.0

In [ ]:
display(DisasterTweets.sort_values(["f1"], ascending=False))

,model,glove_size,max_len,dataset,best_epoch,test_loss,test_acc,precision,recall,f1,test_runtime,test_samples_per_second,test_steps_per_second,batch_size
58,BERT large,NaN,159,DisasterTweets,NaN,0.376,0.856,0.855,0.856,0.855059,13.824,110.172,3.472,NaN
56,BERT large,NaN,50,DisasterTweets,2.0,0.401,0.854,0.855,0.854,0.854368,8.282,183.887,5.796,NaN
55,BERT normal,NaN,159,DisasterTweets,2.0,0.375,0.855,0.855,0.855,0.853981,5.155,295.430,9.311,NaN
54,BERT normal,NaN,100,DisasterTweets,2.0,0.389,0.850,0.850,0.850,0.849825,5.331,285.702,9.004,NaN
53,BERT normal,NaN,50,DisasterTweets,2.0,0.395,0.848,0.850,0.848,0.848756,2.962,514.246,16.207,NaN
57,BERT large,NaN,100,DisasterTweets,NaN,0.378,0.844,0.844,0.844,0.844293,13.765,110.645,3.487,NaN
52,BERT tiny,NaN,159,DisasterTweets,10.0,0.406,0.833,0.833,0.833,0.832151,0.735,2071.001,65.271,NaN
50,BERT tiny,NaN,50,DisasterTweets,10.0,0.411,0.833,0.832,0.833,0.832071,0.822,1852.849,58.396,NaN
51,BERT tiny,NaN,100,DisasterTweets,10.0,0.407,0.833,0.832,0.833,0.831407,0.896,1699.858,53.574,NaN
89,LSTM,200.0,500,DisasterTweets,24.0,0.486,0.785,0.777,0.785,0.778389,NaN,NaN,NaN,16.0
94,LSTM,200.0,200,DisasterTweets,4.0,0.573,0.760,0.755,0.760,0.756910,NaN,NaN,NaN,16.0
99,LSTM,300.0,200,DisasterTweets,4.0,0.619,0.759,0.752,0.759,0.754329,NaN,NaN,NaN,16.0
104,LSTM,300.0,500,DisasterTweets,2.0,0.646,0.755,0.748,0.755,0.750053,NaN,NaN,NaN,16.0
106,LSTM,200.0,350,DisasterTweets,4.0,0.618,0.744,0.744,0.744,0.744485,NaN,NaN,NaN,16.0
86,LSTM,200.0,50,DisasterTweets,1.0,1.010,0.724,0.731,0.724,0.727318,NaN,NaN,NaN,16.0
81,LSTM,200.0,100,DisasterTweets,1.0,1.038,0.735,0.722,0.735,0.725275,NaN,NaN,NaN,16.0
76,LSTM,100.0,100,DisasterTweets,2.0,0.782,0.712,0.742,0.712,0.720947,NaN,NaN,NaN,16.0
66,LSTM,100.0,100,DisasterTweets,2.0,0.782,0.712,0.742,0.712,0.720947,NaN,NaN,NaN,16.0
71,LSTM,100.0,50,DisasterTweets,1.0,0.958,0.681,0.634,0.681,0.633678,NaN,NaN,NaN,16.0
61,LSTM,100.0,50,DisasterTweets,1.0,0.958,0.681,0.634,0.681,0.633678,NaN,NaN,NaN,16.0

<center><h1>Podsumowanie</h1></center>
<center><h2>Wnioski</h2></center>
<ol>
  <li>BERT Tiny uzyskał średnio wyższe wyniki (F1 - weighted) niż LSTM na co wpływ może mieć fakt, że wraz z BERT Tiny wykorzystano już wstępnie wytrenowany model (fine-tuning), a LSTM było trenowane od podstaw. Dodatkowo BERT z tą samą liczbą parametrów/wag do wyuczenia wydaje się lepiej obsługiwać dłuższe sekwencję - prawdopodobnie dzięki mechanizmowi atencji.</li>
  <li>Wykorzystując fine-tuning w BERT z tą samą liczbą parametrów co LSTM trenowana od podstaw, trenuje się szybciej, istnieje opcja by zrównoleglić obliczenia oraz zazwyczaj daje lepsze wyniki (dokładność, wskaźnik F1, precyzja, recall). Mechanizm atencji wydaje się dawać lepsze rezultaty niż komórki pamięci LSTM.</li>
  <li>Im większy model BERT tym zazwyczaj lepsze wyniki, lecz wyraźną różnicę widać przy dłuższych sekwencjach - standardowy model BERT oraz wersja large dają lepsze wyniki dla dłuższych sekwencji. Niestety wykorzystanie dużych modeli (normal 24 razy większy od tiny, oraz large 75 razy większy od tiny) wymaga wielokrotnie dłuższych obliczeń oraz pamięci GPU - co może być czasem nieosiągalne do zapewnienia. Do treningu wykorzystano kartę z 16GB pamięci co jest drogim kosztem, czas obliczeń to około 200h, pomimo takiej ilości pamięci, niektóre zbiory danych nie mieściły się pomimo użycia małego batch_size.</li>
  <li>Nie zawsze użycie dużo większego modelu dawało lepsze rezultaty , szczególnie dla krótkich sekwencji - prawdopodobnie przez wzrost ryzyka nadmiernego dopasowania.</li>
  <li>Często ważniejsza od wielkości modelu była długość przetwarzanej sekwencji, najmniejszy model BERT często dla długich sekwencji liczył się dość szybko oraz dawał dobre rezultaty jednocześnie przy małym zapotrzebowaniu na pamięć GPU.</li>
  <li>Zwiększenie rozmiarów glove wydaje się nie mieć wpływu na jakość działania LSTM - prawdpodobnie trzeba rozmiar glove ustalić jako hiperparametr argumentu i do każdego zbioru/wielkości modelu dobrać glove indywidualnie.</li>
</ol>
<center><h2>Możliwe dalsze kierunki</h2></center>
<ol>
  <li>Porównanie innej sieci LSTM np: CNN-LSTM, dwukierunkowa sieć LSTM, sieć LSTM z mechanizmem atencji.</li>
  <li>Wykorzystanie do badań mechanizmu destylacji wiedzy i porównanie modeli BERT poddanych destylacji (a w szczególności BERT Tiny) z normalnymi oraz LSTM zwykłą o tej samej liczbie parametrów/destylowanej.</li>
  <li>Wykorzystanie zespołu modeli do uzyskania lepszych wyników, np. różne rodzaje BERT + LSTM w celu osiągnięcia wyników state-of-the-art.</li>
  <li>Wykorzystanie innej wersji metody klasyfikacji niż tej opierającej się na tokenie CLS - np. average (uśrednianie) lub pooling/max.pooling.</li>
</ol>